export default {
	growthRatio: 0.05,
	actions: {
		EXAMPLE: 'EXAMPLE_MUTATION',
		BUY_GENERATOR: 'BUY_GENERATOR',
		INCREMENT_CLICK: 'INCREMENT_CLICK',
		CHECK_STORY: 'CHECK_STORY',
		INCREMENT: 'INCREMENT'
	}
};
